/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PickUpRouteImport } from './routes/pick-up'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as DineInRouteImport } from './routes/dine-in'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PickUpTokenRouteImport } from './routes/pick-up_.$token'
import { Route as DineInTokenRouteImport } from './routes/dine-in_.$token'
import { Route as BookTokenRouteImport } from './routes/book.$token'

const PickUpRoute = PickUpRouteImport.update({
  id: '/pick-up',
  path: '/pick-up',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const DineInRoute = DineInRouteImport.update({
  id: '/dine-in',
  path: '/dine-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickUpTokenRoute = PickUpTokenRouteImport.update({
  id: '/pick-up_/$token',
  path: '/pick-up/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DineInTokenRoute = DineInTokenRouteImport.update({
  id: '/dine-in_/$token',
  path: '/dine-in/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTokenRoute = BookTokenRouteImport.update({
  id: '/book/$token',
  path: '/book/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dine-in': typeof DineInRoute
  '/menu': typeof MenuRoute
  '/pick-up': typeof PickUpRoute
  '/book/$token': typeof BookTokenRoute
  '/dine-in/$token': typeof DineInTokenRoute
  '/pick-up/$token': typeof PickUpTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dine-in': typeof DineInRoute
  '/menu': typeof MenuRoute
  '/pick-up': typeof PickUpRoute
  '/book/$token': typeof BookTokenRoute
  '/dine-in/$token': typeof DineInTokenRoute
  '/pick-up/$token': typeof PickUpTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dine-in': typeof DineInRoute
  '/menu': typeof MenuRoute
  '/pick-up': typeof PickUpRoute
  '/book/$token': typeof BookTokenRoute
  '/dine-in_/$token': typeof DineInTokenRoute
  '/pick-up_/$token': typeof PickUpTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dine-in'
    | '/menu'
    | '/pick-up'
    | '/book/$token'
    | '/dine-in/$token'
    | '/pick-up/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dine-in'
    | '/menu'
    | '/pick-up'
    | '/book/$token'
    | '/dine-in/$token'
    | '/pick-up/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dine-in'
    | '/menu'
    | '/pick-up'
    | '/book/$token'
    | '/dine-in_/$token'
    | '/pick-up_/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DineInRoute: typeof DineInRoute
  MenuRoute: typeof MenuRoute
  PickUpRoute: typeof PickUpRoute
  BookTokenRoute: typeof BookTokenRoute
  DineInTokenRoute: typeof DineInTokenRoute
  PickUpTokenRoute: typeof PickUpTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pick-up': {
      id: '/pick-up'
      path: '/pick-up'
      fullPath: '/pick-up'
      preLoaderRoute: typeof PickUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dine-in': {
      id: '/dine-in'
      path: '/dine-in'
      fullPath: '/dine-in'
      preLoaderRoute: typeof DineInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick-up_/$token': {
      id: '/pick-up_/$token'
      path: '/pick-up/$token'
      fullPath: '/pick-up/$token'
      preLoaderRoute: typeof PickUpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dine-in_/$token': {
      id: '/dine-in_/$token'
      path: '/dine-in/$token'
      fullPath: '/dine-in/$token'
      preLoaderRoute: typeof DineInTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$token': {
      id: '/book/$token'
      path: '/book/$token'
      fullPath: '/book/$token'
      preLoaderRoute: typeof BookTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DineInRoute: DineInRoute,
  MenuRoute: MenuRoute,
  PickUpRoute: PickUpRoute,
  BookTokenRoute: BookTokenRoute,
  DineInTokenRoute: DineInTokenRoute,
  PickUpTokenRoute: PickUpTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
